### ISSUE TITLE
Readme.md Datei Beschwerde!

### ISSUE THREAD

**Issue by LindelAlexander** [PatCer/DevOpsPaketeRepo#1]
Sehr geehrter Herr Cerna,

Ich wollte mir ihr wunderschönes Repository ansehen, musste aber leider bemerken das die ReadME.md Datei sehr schwer aufzufinden ist. Vor allem für unerfahrene Nutzer kann dies zu Verwirrung führen, daher bitte ich Sie die Readme außerhalb des Ordners zu positionieren. 

Des weiteren würde ich die ReadMe etwas mehr Überarbeiten, vor allem das nutzen von Bildern und das nutzen von Unterpunkten könnte die Struktur ihres Repos erheblich verbessern.

Ich hoffe sie nehmen sich diese Vorschläge zu Herzen. LG Elalex

**Comment by JannicHeidrich** [comment]
Hello im Jannic,

yes, I have also noticed this problem inexperienced users often have the problem that they do not know how to create their readme correctly

Your sincerely Eljannic

**Comment by PatCer** [comment]
Hi @JannicHeidrich, @AlexLPlanB ,

Thank you for bringing this to our attention. We appreciate your diligence in pointing out the issues with the README placement and the absence of pictures.

I'm glad to inform you that the concerns have been addressed. The README has been moved to the correct file, and visual content, including pictures, has been added to enhance the documentation.

If you have any further questions, encounter additional issues, or if there's anything else you'd like to discuss, please feel free to let us know. Your feedback is valuable, and we're here to help.

Best regards,
PatCer
DevOpsPaketeRepo
