### ISSUE TITLE
Falsche Datumsangabe in Userstory2and3 Projekt

### ISSUE THREAD

**Issue by LindelAlexander** [PatCer/DevOpsPaketeRepo#2]
Sehr geehrter Herr Cerna,

ich musste heute Leider feststellen, das in ihrer IoTMessageRessourceTemplate.bicep Datei die Datumse in ihrem Code leider noch die von 2021 sind und nicht die von 2023. Daher bitte ich Sie dies zu ändern um die Funktionsfähigkeit ihres Programms zu gewährleisten.

Hier ein Beispiel Bild:
![image](https://github.com/PatCer/DevOpsPaketeRepo/assets/159454517/9f11cfc3-cd10-43e4-a665-7355b74fc814)

Liebe Grüße, Alex =)

**Comment by LindelAlexander** [comment]
Guten Tag Herr Cerna, ich wollte mich erkundigen ob sie den Fehler bereits behoben haben.. LG Alex

**Comment by PatCer** [comment]
Ja ist gefixt.
